import 'package:sooq/features/Home/data/models/products_model.dart';

class ProductConstants {
  static List<Product> byIndex(int index) {
    switch (index) {
      case 0:
        return vegetables;
      case 1:
        return fruits;
      case 2:
        return dairy;
      case 3:
        return proteins;
      case 4:
        return laundry;
      default:
        return vegetables;
    }
  }

  static List<Product> get all => [
    ...ProductConstants.vegetables,
    ...ProductConstants.fruits,
    ...ProductConstants.dairy,
    ...ProductConstants.proteins,
    ...ProductConstants.laundry,
  ];

  static const List<Product> dairy = [
    Product(
      image: 'assets/img/product/dairy/almondmilk.png',
      name: 'almondmilk',
      rate: 3.6,
      price: 11,
      votes: 100,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/bread.png',
      name: 'bread',
      rate: 3.8,
      price: 44,
      votes: 108,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/butternatural.png',
      name: 'butternatural',
      rate: 3.1,
      price: 88,
      votes: 1900,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/cheese.png',
      name: 'cheese',
      rate: 3.6,
      price: 72,
      votes: 188,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/cheesethumb.png',
      name: 'cheesethumb',
      rate: 4.0,
      price: 19,
      votes: 560,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/Chocolatemilk.png',
      name: 'Chocolatemilk',
      rate: 3.2,
      price: 51,
      votes: 671,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/egg.png',
      name: 'egg',
      rate: 3.3,
      price: 79,
      votes: 300,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/pngtreecheese.png',
      name: 'pngtreecheese',
      rate: 3.7,
      price: 77,
      votes: 500,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/riceoriginal.png',
      name: 'riceoriginal',
      rate: 3.1,
      price: 75,
      votes: 750,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/strawberr.png',
      name: 'strawberr',
      rate: 3.9,
      price: 44,
      votes: 800,
      category: 'dairy',
    ),
    Product(
      image: 'assets/img/product/dairy/yogurt.png',
      name: 'yogurt',
      rate: 4.0,
      price: 3,
      votes: 504,
      category: 'dairy',
    ),
  ];

  static const List<Product> fruits = [
    Product(
      image: 'assets/img/product/fruits/strawberry.png',
      name: 'strawberry',
      rate: 3.6,
      price: 35,
      votes: 808,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/Tangerines.png',
      name: 'Tangerines',
      rate: 3.1,
      price: 5,
      votes: 1000,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/pineapple.png',
      name: 'pineapple',
      rate: 3.5,
      price: 88,
      votes: 208,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/banana.png',
      name: 'banana',
      rate: 3.7,
      price: 22,
      votes: 255,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/kiwi.png',
      name: 'kiwi',
      rate: 3.5,
      price: 88,
      votes: 205,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/mango.png',
      name: 'mango',
      rate: 4.0,
      price: 66,
      votes: 600,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/lemon.png',
      name: 'lemon',
      rate: 4.0,
      price: 88,
      votes: 600,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/orange.png',
      name: 'orange',
      rate: 3.8,
      price: 33,
      votes: 333,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/pepper.png',
      name: 'pepper',
      rate: 2.8,
      price: 12,
      votes: 55,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/avocado.png',
      name: 'avocado',
      rate: 4.0,
      price: 55,
      votes: 200,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/cherries.png',
      name: 'cherries',
      rate: 3.9,
      price: 800,
      votes: 600,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/grape.png',
      name: 'grape',
      rate: 4.0,
      price: 600,
      votes: 55,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/guava.png',
      name: 'guava',
      rate: 2.8,
      price: 12,
      votes: 55,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/watermelon.png',
      name: 'watermelon',
      rate: 3.8,
      price: 55,
      votes: 100,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/pomegranate.png',
      name: 'pomegranate',
      rate: 3.3,
      price: 88,
      votes: 550,
      category: 'fruits',
    ),
    Product(
      image: 'assets/img/product/fruits/safandy.png',
      name: 'safandy',
      rate: 3.8,
      price: 99,
      votes: 405,
      category: 'fruits',
    ),
  ];

  static const List<Product> vegetables = [
    Product(
      image: 'assets/img/product/vegetables/hotpepper.png',
      name: 'hotpepper',
      rate: 3.7,
      price: 15,
      votes: 200,
      category: 'vegetables',
    ),
    Product(
      image: 'assets/img/product/vegetables/potatoes.png',
      name: 'potatoes',
      rate: 3.6,
      price: 22,
      votes: 705,
      category: 'vegetables',
    ),
    Product(
      image: 'assets/img/product/vegetables/tomatoes.png',
      name: 'tomatoes',
      rate: 3.8,
      price: 35,
      votes: 200,
      category: 'vegetables',
    ),
    Product(
      image: 'assets/img/product/vegetables/Vealmeat.png',
      name: 'Vealmeat',
      rate: 3.7,
      price: 5,
      votes: 22,
      category: 'vegetables',
    ),
  ];

  static const List<Product> proteins = [
    Product(
      image: 'assets/img/product/protiens/Bonelessfish.png',
      name: 'Bonelessfish',
      rate: 3.9,
      price: 500,
      votes: 1000,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Chickenthighs.png',
      name: 'Chickenthighs',
      rate: 3.9,
      price: 900,
      votes: 8000,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Chicken.png',
      name: 'Chicken',
      rate: 3.5,
      price: 100,
      votes: 500,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/fish.png',
      name: 'Fish',
      rate: 3.2,
      price: 400,
      votes: 700,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/FishClipart.png',
      name: 'FishClipart',
      rate: 2.8,
      price: 36,
      votes: 200,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Meatfeathers.png',
      name: 'Meatfeathers',
      rate: 3.5,
      price: 500,
      votes: 2200,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/mincedmeat.png',
      name: 'mincedmeat',
      rate: 2.8,
      price: 700,
      votes: 4200,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/RawMeat.png',
      name: 'rawmeat',
      rate: 4.0,
      price: 1100,
      votes: 200,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Salmonfish.png',
      name: 'Salmonfish',
      rate: 3.8,
      price: 500,
      votes: 900,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Shrimp.png',
      name: 'Shrimp',
      rate: 3.8,
      price: 250,
      votes: 3200,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Transparent.png',
      name: 'Transparent',
      rate: 3.9,
      price: 1500,
      votes: 1000,
      category: 'proteins',
    ),
    Product(
      image: 'assets/img/product/protiens/Vealmeat.png',
      name: 'Vealmeat',
      rate: 3.8,
      price: 800,
      votes: 100,
      category: 'proteins',
    ),
  ];

  static const List<Product> laundry = [
    Product(
      image: 'assets/img/product/laundry/Crump.png',
      name: 'Crump',
      rate: 3.2,
      price: 55,
      votes: 740,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/downyfabric.png',
      name: 'downyfabric',
      rate: 3.1,
      price: 11,
      votes: 770,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/downy-fabricr.png',
      name: 'downy-fabricr',
      rate: 3.8,
      price: 77,
      votes: 880,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/mountainc.png',
      name: 'mountainc',
      rate: 3.7,
      price: 5,
      votes: 777,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/pngimg.png',
      name: 'pngimg',
      rate: 4.0,
      price: 7,
      votes: 100,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/softener-.png',
      name: 'softener-',
      rate: 2.2,
      price: 22,
      votes: 201,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/tideantibacterial.png',
      name: 'tideantibacterial',
      rate: 3.8,
      price: 77,
      votes: 540,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/tidepods.png',
      name: 'tidepods',
      rate: 4.0,
      price: 44,
      votes: 821,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/washing1.png',
      name: 'washing1',
      rate: 3.8,
      price: 11,
      votes: 222,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/washing2.png',
      name: 'washing2',
      rate: 3.9,
      price: 8,
      votes: 590,
      category: 'laundry',
    ),
    Product(
      image: 'assets/img/product/laundry/washing3.png',
      name: 'washing3',
      rate: 2.8,
      price: 9,
      votes: 1050,
      category: 'laundry',
    ),
  ];
}
