import 'package:market_salla/models/products_model.dart';


   List<List<Products>> sectionsOfProducts = [
    [
      Products(
        image: "assets/img/product/dairy/almondmilk.png",
        name: "almondmilk",
        rate: "3.6",
        price: "\$11",
        votes: "100",
      ),
      Products(
        image: "assets/img/product/dairy/bread.png",
        name: "bread",
        rate: "3.8",
        price: "\$44",
        votes: "108",
      ),
      Products(
        image: "assets/img/product/dairy/butternatural.png",
        name: "butternatural",
        rate: "3.1",
        price: "\$88",
        votes: "1900",
      ),
      Products(
        image: "assets/img/product/dairy/cheese.png",
        name: "cheese",
        rate: "3.6",
        price: "\$71",
        votes: "188",
      ),
      Products(
        image: "assets/img/product/dairy/cheesethumb.png",
        name: "cheesethumb",
        rate: "4.0",
        price: "\$19",
        votes: "560",
      ),
      Products(
        image: "assets/img/product/dairy/Chocolatemilk.png",
        name: "Chocolatemilk",
        rate: "3.2",
        price: "\$51",
        votes: "671",
      ),
      Products(
        image: "assets/img/product/dairy/egg.png",
        name: "egg",
        rate: "3.3",
        price: "\$79",
        votes: "300",
      ),
      Products(
        image: "assets/img/product/dairy/pngtreecheese.png",
        name: "pngtreecheese",
        rate: "3.7",
        price: "\$77",
        votes: "500",
      ),
      Products(
        image: "assets/img/product/dairy/riceoriginal.png",
        name: "riceoriginal",
        rate: "3.1",
        price: "\$75",
        votes: "750",
      ),
      Products(
        image: "assets/img/product/dairy/strawberr.png",
        name: "strawberr",
        rate: "3.9",
        price: "\$44",
        votes: "800",
      ),
      Products(
        image: "assets/img/product/dairy/yogurt.png",
        name: "yogurt.png",
        rate: "4.0",
        price: "\$3",
        votes: "504",
      ),
    ],
    [
      Products(
        image: "assets/img/product/fruits/strawberry.png",
        name: "strawberry",
        rate: "3.6",
        price: "\$35",
        votes: "808",
      ),
      Products(
        image: "assets/img/product/fruits/Tangerines.png",
        name: "Tangerines",
        rate: "3.1",
        price: "\$5",
        votes: "1000",
      ),
      Products(
        image: "assets/img/product/fruits/pineapple.png",
        name: "pineapple",
        rate: "3.5",
        price: "\$88",
        votes: "208",
      ),
      Products(
        image: "assets/img/product/fruits/banana.png",
        name: "banana",
        rate: "3.7",
        price: "\$22",
        votes: "255",
      ),
      Products(
        image: "assets/img/product/fruits/kiwi.png",
        name: "kiwi",
        rate: "3.5",
        price: "\$88",
        votes: "205",
      ),
      Products(
        image: "assets/img/product/fruits/mango.png",
        name: "mango",
        rate: "4.0",
        price: "\$66",
        votes: "600",
      ),
      Products(
        image: "assets/img/product/fruits/lemon.png",
        name: "lemon",
        rate: "4.0",
        price: "\$88",
        votes: "600",
      ),
      Products(
        image: "assets/img/product/fruits/orange.png",
        name: "orange",
        rate: "3.8",
        price: "\$33",
        votes: "333",
      ),
      Products(
        image: "assets/img/product/fruits/pepper.png",
        name: "pepper",
        rate: "2.8",
        price: "\$12",
        votes: "55",
      ),
      Products(
        image: "assets/img/product/fruits/avocado.png",
        name: "avocado",
        rate: "4.0",
        price: "\$55",
        votes: "200",
      ),
      Products(
        image: "assets/img/product/fruits/cherries.png",
        name: "cherries",
        rate: "3.9",
        price: "\$800",
        votes: "600",
      ),
      Products(
        image: "assets/img/product/fruits/grape.png",
        name: "grape.png",
        rate: "4.0",
        price: "\$600",
        votes: "55",
      ),
      Products(
        image: "assets/img/product/fruits/guava.png",
        name: "guava",
        rate: "2.8",
        price: "\$12",
        votes: "55",
      ),
      Products(
        image: "assets/img/product/fruits/watermelon.png",
        name: "watermelon",
        rate: "3.8",
        price: "\$55",
        votes: "100",
      ),
      Products(
        image: "assets/img/product/fruits/pomegranate.png",
        name: "pomegranate",
        rate: "3.3",
        price: "\$88",
        votes: "550",
      ),
      Products(
        image: "assets/img/product/fruits/safandy.png",
        name: "safandy",
        rate: "3.8",
        price: "\$99",
        votes: "405",
      ),
    ],
    [
      Products(
        image: "assets/img/product/laundry/Crump.png",
        name: "Crump",
        rate: "3.2",
        price: "\$55",
        votes: "740",
      ),
      Products(
        image: "assets/img/product/laundry/downyfabric.png",
        name: "downyfabric",
        rate: "3.1",
        price: "\$11",
        votes: "770",
      ),
      Products(
        image: "assets/img/product/laundry/downy-fabricr.png",
        name: "downy-fabricr",
        rate: "3.8",
        price: "\$77",
        votes: "880",
      ),
      Products(
        image: "assets/img/product/laundry/mountainc.png",
        name: "mountainc.png",
        rate: "3.7",
        price: "\$5",
        votes: "777",
      ),
      Products(
        image: "assets/img/product/laundry/pngimg.png",
        name: "pngimg",
        rate: "4.0",
        price: "\$7",
        votes: "100",
      ),
      Products(
        image: "assets/img/product/laundry/softener-.png",
        name: "softener-",
        rate: "2.2",
        price: "\$22",
        votes: "201",
      ),
      Products(
        image: "assets/img/product/laundry/tideantibacterial.png",
        name: "tideantibacterial",
        rate: "3.8",
        price: "\$77",
        votes: "540",
      ),
      Products(
        image: "assets/img/product/laundry/tidepods.png",
        name: "tidepods",
        rate: "4.0",
        price: "\$44",
        votes: "821",
      ),
      Products(
        image: "assets/img/product/laundry/washing1.png",
        name: "washing1",
        rate: "3.8",
        price: "\$11",
        votes: "222",
      ),
      Products(
        image: "assets/img/product/laundry/washing2.png",
        name: "washing2",
        rate: "3.9",
        price: "\$8",
        votes: "590",
      ),
      Products(
        image: "assets/img/product/laundry/washing3.png",
        name: "washing3",
        rate: "2.8",
        price: "\$9",
        votes: "1050",
      ),
    ],
    [
      Products(
        image: "assets/img/product/vegetables/broccoli.png",
        name: "broccoli",
        rate: "3.7",
        price: "\$33",
        votes: "88",
      ),
      Products(
        image: "assets/img/product/vegetables/Cabbage.png",
        name: "Cabbage",
        rate: "3.9",
        price: "\$11",
        votes: "800",
      ),
      Products(
        image: "assets/img/product/vegetables/carrot.png",
        name: "carrot",
        rate: "3.9",
        price: "\$2",
        votes: "700",
      ),
      Products(
        image: "assets/img/product/vegetables/corn.png",
        name: "corn",
        rate: "3.9",
        price: "\$22",
        votes: "100",
      ),
      Products(
        image: "assets/img/product/vegetables/Crump.png",
        name: "Crump",
        rate: "3.9",
        price: "\$22",
        votes: "100",
      ),
      Products(
        image: "assets/img/product/vegetables/cucumber.png",
        name: "cucumber",
        rate: "3.7",
        price: "\$22",
        votes: "500",
      ),
      Products(
        image: "assets/img/product/vegetables/Eggplant.png",
        name: "Eggplant",
        rate: "3.9",
        price: "\$11",
        votes: "111",
      ),
      Products(
        image: "assets/img/product/vegetables/hot pepper.png",
        name: "hot pepper",
        rate: "3.7",
        price: "\$15",
        votes: "200",
      ),
      Products(
        image: "assets/img/product/vegetables/potatoes.png",
        name: "potatoes",
        rate: "3.6",
        price: "\$22",
        votes: "705",
      ),
      Products(
        image: "assets/img/product/vegetables/tomatoes.png",
        name: "tomatoes",
        rate: "3.8",
        price: "\$35",
        votes: "200",
      ),
      Products(
        image: "assets/img/product/vegetables/Veal meat.png",
        name: "Veal meat",
        rate: "3.7",
        price: "\$5",
        votes: "22",
      ),
    ],
    [
      Products(
        image: "assets/img/product/protiens/Boneless fish.png",
        name: "Boneless fish",
        rate: "3.9",
        price: "\$500",
        votes: "1000",
      ),
      Products(
        image: "assets/img/product/protiens/Boneless shrimp.png",
        name: "Boneless shrimp",
        rate: "4.0",
        price: "\$400",
        votes: "2050",
      ),
      Products(
        image: "assets/img/product/protiens/Chicken thighs.png",
        name: "Chicken thighs",
        rate: "3.9",
        price: "\$900",
        votes: "8000",
      ),
      Products(
        image: "assets/img/product/protiens/Chicken.png",
        name: "Chicken",
        rate: "3.5",
        price: "\$100",
        votes: "500",
      ),

      Products(
        image: "assets/img/product/protiens/fish.png",
        name: "Fish",
        rate: "3.2",
        price: "\$400",
        votes: "700",
      ),
      Products(
        image: "assets/img/product/protiens/FishClipart.png",
        name: "FishClipart",
        rate: "2.8",
        price: "\$36",
        votes: "200",
      ),
      Products(
        image: "assets/img/product/protiens/Meat feathers.png",
        name: "Meat feathers",
        rate: "3.5",
        price: "\$500",
        votes: "2200",
      ),
      Products(
        image: "assets/img/product/protiens/minced meat.png",
        name: "minced meat",
        rate: "2.8",
        price: "\$700",
        votes: "4200",
      ),
      Products(
        image: "assets/img/product/protiens/RawMeat.png",
        name: "rawmeat",
        rate: "4.0",
        price: "\$1100",
        votes: "200",
      ),
      Products(
        image: "assets/img/product/protiens/Salmon fish.png",
        name: "Salmon fish",
        rate: "3.8",
        price: "\$500",
        votes: "900",
      ),
      Products(
        image: "assets/img/product/protiens/Shrimp.png",
        name: "Shrimp",
        rate: "3.8",
        price: "\$250",
        votes: "3200",
      ),
      Products(
        image: "assets/img/product/protiens/Transparent.png",
        name: "Transparent",
        rate: "3.9",
        price: "\$1500",
        votes: "1000",
      ),
      Products(
        image: "assets/img/product/protiens/Veal meat.png",
        name: "Veal meat",
        rate: "3.8",
        price: "\$800",
        votes: "100",
      ),
    ],
  ];
