// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu27PGwV6PpP-x9lx6Cs7flkRAxJVQ_Ug',
    appId: '1:305087084413:web:857b3fda61102108677e14',
    messagingSenderId: '305087084413',
    projectId: 'salla-5da21',
    authDomain: 'salla-5da21.firebaseapp.com',
    storageBucket: 'salla-5da21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbHvjzSfbc9n7n-HJqIkT3ibgOCXaIz-s',
    appId: '1:305087084413:android:d34228897b8a3851677e14',
    messagingSenderId: '305087084413',
    projectId: 'salla-5da21',
    storageBucket: 'salla-5da21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT12GvxjC7WmnauuFDORn9AmWFybO_FcU',
    appId: '1:305087084413:ios:bdb053fe5695fc4b677e14',
    messagingSenderId: '305087084413',
    projectId: 'salla-5da21',
    storageBucket: 'salla-5da21.firebasestorage.app',
    androidClientId: '305087084413-nmb1k2m07cel12758jvte65aei2qcgv0.apps.googleusercontent.com',
    iosClientId: '305087084413-0tahq3ftvp8q8vn60n9bl0d1vcnulbpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketSalla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT12GvxjC7WmnauuFDORn9AmWFybO_FcU',
    appId: '1:305087084413:ios:bdb053fe5695fc4b677e14',
    messagingSenderId: '305087084413',
    projectId: 'salla-5da21',
    storageBucket: 'salla-5da21.firebasestorage.app',
    androidClientId: '305087084413-nmb1k2m07cel12758jvte65aei2qcgv0.apps.googleusercontent.com',
    iosClientId: '305087084413-0tahq3ftvp8q8vn60n9bl0d1vcnulbpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketSalla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu27PGwV6PpP-x9lx6Cs7flkRAxJVQ_Ug',
    appId: '1:305087084413:web:4d43af738b9d745f677e14',
    messagingSenderId: '305087084413',
    projectId: 'salla-5da21',
    authDomain: 'salla-5da21.firebaseapp.com',
    storageBucket: 'salla-5da21.firebasestorage.app',
  );
}
